From info-gbe=unobtanium.de@ceoannualmeet.info Sun Oct 18 23:46:34 2020
Return-Path: <info-gbe=unobtanium.de@ceoannualmeet.info>
Delivered-To: gbe@unobtanium.de
Received: from ceo9.ceoannualmeet.info (ip240.ip-51-38-153.eu [51.38.153.240])
	by mariner.unobtanium.de (OpenSMTPD) with ESMTP id 894cc354
	for <gbe@unobtanium.de>;
	Sun, 18 Oct 2020 23:46:34 +0200 (CEST)
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; s=default; d=ceoannualmeet.info;
 h=Date:To:From:Reply-To:Subject:Message-ID:List-Unsubscribe:List-Id:MIME-Version:Content-Type; i=info@ceoannualmeet.info;
 bh=aalJ7RCPA7XoWFkUwguGAjlaMuk=;
 b=Y8Pw+Q+d6KZ7+P49JVVV2cjoa22BN8mxTZgW9EhS1TG7Z6m9gJCHElIxtOoInr7HhdBcEGIMJ1Xm
   sojq/ZQWaI3WFQBq9pqeSeRZY+4ClGjekjKrXvPf/KPdlM24e9e6QbD2M7lMK7Afo9UeJkKDOKik
   5JWPfMKe7TOVFxHrSnM2FKEsZcLYzwO49DjYNTn8g7/3oEKdGspii3uyzkqN9aomjDcAX2MwLwKb
   E1bOPjGoEFpEbfb3sv1aNvAj0o7AZqXuXNec94EZILfL6RiKzrKAJ2woVEmZa4lnY2d5JZHfnx5d
   G9xrmUo30ftpgeQljkTDTuor4jaliqwa3EAhzg==
DomainKey-Signature: a=rsa-sha1; c=nofws; q=dns; s=default; d=ceoannualmeet.info;
 b=c6YIXTPLwGS3wFGTawj0vD9QdvgvGo4jTxdqd/qA1FSsgeyhfnKh2lnnjAwmq1ptKxiXVGaeE+W7
   WpDQNyhkI/Cy+PzOogU94++uQTZaTyypFQ4ThytPAK6DtwL9BVahXeSnGmcGj4HMETUTHLRM0zWm
   61vrnoQlLtsra4HLjhqaAT2l6oJ+2E5rBesLg+HiPSrSnW4te1ydfaQ1t58fIeybVGHV4yZrJiwN
   587kmAOHnFvmm+xamBfmiPUVdCZDOysx4BJUINrJWtlbLepkPGGLmnLqs35tbcuVCMOTNm6UhAsP
   x9J4/CTwF7jqcNSkxttUIBLbA58QkM/KifIvxw==;
Received: from ceoannualmeet.info (51.68.136.236) by ceo1.ceoannualmeet.info id hhirrli19tkk for <gbe@unobtanium.de>; Sun, 18 Oct 2020 21:46:13 +0000 (envelope-from <info-gbe=unobtanium.de@ceoannualmeet.info>)
Date: Sun, 18 Oct 2020 21:46:13 +0000
To: "gbe@unobtanium.de" <gbe@unobtanium.de>
From: Emma Johnson <info@ceoannualmeet.info>
Reply-To: Emma Johnson <emma@ceoeventsummit2020.info>
Subject: RE: 10 Leads and Scheduled appointments at 1k
Message-ID: <184bc52548de23b8c2075b3fa6499377@ceoannualmeet.info>
X-Pmcq-Campaign-Uid: th193qgnlz6fe
X-Pmcq-Subscriber-Uid: mk292fjs8kc43
X-Pmcq-Customer-Uid: ch943oplfr30d
X-Pmcq-Customer-Gid: 0
X-Pmcq-Delivery-Sid: 1
X-Pmcq-Tracking-Did: 0
List-Unsubscribe: <https://ceoannualmeet.info/eml/index.php/lists/et8087yaom4d1/unsubscribe/mk292fjs8kc43/th193qgnlz6fe/unsubscribe-direct?source=email-client-unsubscribe-button>, <mailto:emma@ceoeventsummit2020.info?subject=Campaign-Uid:th193qgnlz6fe / Subscriber-Uid:mk292fjs8kc43 - Unsubscribe request&body=Please unsubscribe me!>
List-Id: et8087yaom4d1 <NN3>
X-Report-Abuse: Please report abuse for this campaign here: https://ceoannualmeet.info/eml/index.php/campaigns/th193qgnlz6fe/report-abuse/et8087yaom4d1/mk292fjs8kc43
Feedback-ID: th193qgnlz6fe:mk292fjs8kc43:et8087yaom4d1:ch943oplfr30d
Precedence: bulk
X-Pmcq-EBS: https://ceoannualmeet.info/eml/index.php/lists/block-address
Return-Path: info@ceoannualmeet.info
X-Sender: info@ceoannualmeet.info
X-Receiver: gbe@unobtanium.de
X-Pmcq-Mailer: PHPMailer - 5.2.21
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="b1_2e74f31dfe3aff44ccf9bd075cc8f0ce"
X-Bogosity: Unsure, tests=bogofilter, spamicity=0.934963, version=1.2.5
Status: RO
Content-Length: 2533

This is a multi-part message in MIME format.

--b1_2e74f31dfe3aff44ccf9bd075cc8f0ce
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

Are you interested to get qualified leads and customer queries for
your business?
Option 1:10 Leads generated from email marketing to your target
audience at $1,000
Option 2:10 Scheduled appointments from Tele calling to your target
audience at $1,500
We have targeted database from your industry and we just need your
service/sales pitch, we will create an email pitch and tele calling
script. Share with you before we start sending that to your target
audience to generate Leads or queries.
Please reply to this email if wish to know more about this Lead
generation. Also if you can share your target audience details like
titles/industry/location or type of audience you target for your
business.
Thanks,
Emma Johnson
Lead generation Team
+1-(678) 745-8385
Email Marketing Inc
Unsubscribe
https://ceoannualmeet.info/eml/index.php/lists/et8087yaom4d1/unsubscribe/mk=
292fjs8kc43/th193qgnlz6fe


--b1_2e74f31dfe3aff44ccf9bd075cc8f0ce
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html>
<html>
<head><meta charset=3D"utf-8"/>
=09<title></title>
</head>
<body>Are you interested to get qualified leads and customer queries for yo=
ur business?<br />
<br />
Option 1:10 Leads generated from email marketing to your target audience at=
 $1,000<br />
Option 2:10 Scheduled appointments from Tele calling to your target audienc=
e at $1,500<br />
<br />
We have targeted database from your industry and we just need your service/=
sales pitch, we will create an email pitch and tele calling script. Share w=
ith you before we start sending that to your target audience to generate Le=
ads or queries.<br />
<br />
Please reply to this email if wish to know more about this Lead generation.=
 Also if you can share your target audience details like titles/industry/lo=
cation or type of audience you target for your business.<br />
<br />
Thanks,<br />
<br />
Emma Johnson<br />
Lead generation Team<br />
+1-(678) 745-8385<br />
Email Marketing Inc<br />
<br />
<br />
<br />
<br />
<a href=3D"https://ceoannualmeet.info/eml/index.php/lists/et8087yaom4d1/uns=
ubscribe/mk292fjs8kc43/th193qgnlz6fe">Unsubscribe</a><img width=3D"1" heigh=
t=3D"1" src=3D"https://ceoannualmeet.info/eml/index.php/campaigns/th193qgnl=
z6fe/track-opening/mk292fjs8kc43" alt=3D"" />=0A</body>
</html>


--b1_2e74f31dfe3aff44ccf9bd075cc8f0ce--


