name: Lint

on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v1.2.1
      with:
        version: v1.29

